// Mock data for Venus 3D Creations

export const LOGO_URL = "https://customer-assets-m6fa6gv7.emergentagent.net/job_venus-v2/artifacts/urm3257g_Logo.webp";

export const categories = [
  {
    id: "lamps",
    name: "Sculptural Lamps",
    tagline: "Illuminate with art",
    image: "https://images.unsplash.com/photo-1732552599124-f3dd512c02ff?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjY2NzZ8MHwxfHNlYXJjaHwzfHwzRCUyMHByaW50ZWQlMjBsYW1wfGVufDB8fHx8MTc4NTE1NzU5OHww&ixlib=rb-4.1.0&q=85",
  },
  {
    id: "handbags",
    name: "Statement Handbags",
    tagline: "Wearable geometry",
    image: "https://images.unsplash.com/photo-1589363358751-ab05797e5629?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA3MDR8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBoYW5kYmFnfGVufDB8fHx8MTc4NTE1NzU5OHww&ixlib=rb-4.1.0&q=85",
  },
  {
    id: "sculptures",
    name: "Sculptures",
    tagline: "Form meets emotion",
    image: "https://images.unsplash.com/photo-1672343385650-8d5bb804580a?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDQ2Mzl8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBzY3VscHR1cmV8ZW58MHx8fHwxNzg1MTU3NjA0fDA&ixlib=rb-4.1.0&q=85",
  },
  {
    id: "decor",
    name: "Home Decor",
    tagline: "Curate your space",
    image: "https://images.unsplash.com/photo-1667312939978-64cf31718a6e?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDQ2NDF8MHwxfHNlYXJjaHwzfHxtaW5pbWFsaXN0JTIwZGVjb3J8ZW58MHx8fHwxNzg1MTU3NTk4fDA&ixlib=rb-4.1.0&q=85",
  },
  {
    id: "custom",
    name: "Custom Models",
    tagline: "Your vision, printed",
    image: "https://images.unsplash.com/photo-1691957713140-a9a042252202?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDQ2Mzl8MHwxfHNlYXJjaHwyfHxtb2Rlcm4lMjBzY3VscHR1cmV8ZW58MHx8fHwxNzg1MTU3NjA0fDA&ixlib=rb-4.1.0&q=85",
  },
];

export const products = [
  {
    id: "p1",
    name: "Helix Table Lamp",
    category: "lamps",
    price: 189,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1732552599124-f3dd512c02ff?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjY2NzZ8MHwxfHNlYXJjaHwzfHwzRCUyMHByaW50ZWQlMjBsYW1wfGVufDB8fHx8MTc4NTE1NzU5OHww&ixlib=rb-4.1.0&q=85",
    tag: "New",
    description: "A spiraling silhouette that casts warm, patterned light. Printed in matte biodegradable PLA with a hand-finished satin coat.",
    material: "Matte PLA · Warm LED",
    dimensions: "18 × 18 × 34 cm",
    leadTime: "Ships in 3–5 days",
  },
  {
    id: "p2",
    name: "Lunar Pendant Light",
    category: "lamps",
    price: 249,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1678111731954-edb244cd5880?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NzV8MHwxfHNlYXJjaHwyfHxzY3VscHR1cmFsJTIwbGFtcHxlbnwwfHx8fDE3ODUxNTc2MDR8MA&ixlib=rb-4.1.0&q=85",
    tag: "Best Seller",
    description: "A sculpted moon-like pendant with organic ridges. Diffuses light into soft, dappled patterns.",
    material: "Silk PLA · E27 bulb",
    dimensions: "Ø 32 cm",
    leadTime: "Ships in 5–7 days",
  },
  {
    id: "p3",
    name: "Nova Floor Lamp",
    category: "lamps",
    price: 379,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1665886326878-290958e4ed00?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjY2NzZ8MHwxfHNlYXJjaHw0fHwzRCUyMHByaW50ZWQlMjBsYW1wfGVufDB8fHx8MTc4NTE1NzU5OHww&ixlib=rb-4.1.0&q=85",
    description: "Statement floor lamp inspired by architectural columns. A conversation piece for any modern living room.",
    material: "Reinforced PLA · Dimmable LED",
    dimensions: "25 × 25 × 140 cm",
    leadTime: "Ships in 7–10 days",
  },
  {
    id: "p4",
    name: "Meridian Clutch",
    category: "handbags",
    price: 165,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1589363358751-ab05797e5629?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA3MDR8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBoYW5kYmFnfGVufDB8fHx8MTc4NTE1NzU5OHww&ixlib=rb-4.1.0&q=85",
    tag: "Limited",
    description: "A geometric evening clutch with lattice detailing. Lightweight, printed as one continuous piece.",
    material: "Flex PLA · Vegan lining",
    dimensions: "24 × 6 × 12 cm",
    leadTime: "Ships in 4–6 days",
  },
  {
    id: "p5",
    name: "Prisma Tote",
    category: "handbags",
    price: 220,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1682745230951-8a5aa9a474a0?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA3MDR8MHwxfHNlYXJjaHwyfHxsdXh1cnklMjBoYW5kYmFnfGVufDB8fHx8MTc4NTE1NzU5OHww&ixlib=rb-4.1.0&q=85",
    description: "Structured tote with faceted panels. Printed handles, hand-stitched leather trim.",
    material: "Rigid PLA · Leather trim",
    dimensions: "32 × 12 × 28 cm",
    leadTime: "Ships in 5–7 days",
  },
  {
    id: "p6",
    name: "Facet Mini Bag",
    category: "handbags",
    price: 145,
    currency: "USD",
    image: "https://images.pexels.com/photos/14806252/pexels-photo-14806252.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    description: "A crystalline mini bag with mirror finish. Small enough for essentials, bold enough to be the outfit.",
    material: "Metallic PLA",
    dimensions: "18 × 6 × 14 cm",
    leadTime: "Ships in 4–6 days",
  },
  {
    id: "p7",
    name: "Aura Bust Study",
    category: "sculptures",
    price: 320,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1672343385650-8d5bb804580a?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDQ2Mzl8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBzY3VscHR1cmV8ZW58MHx8fHwxNzg1MTU3NjA0fDA&ixlib=rb-4.1.0&q=85",
    tag: "New",
    description: "A contemporary reinterpretation of the classical bust. Hand-finished with a soft matte patina.",
    material: "Composite resin",
    dimensions: "22 × 18 × 40 cm",
    leadTime: "Ships in 7–10 days",
  },
  {
    id: "p8",
    name: "Waveform Object",
    category: "sculptures",
    price: 265,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1691957713140-a9a042252202?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDQ2Mzl8MHwxfHNlYXJjaHwyfHxtb2Rlcm4lMjBzY3VscHR1cmV8ZW58MHx8fHwxNzg1MTU3NjA0fDA&ixlib=rb-4.1.0&q=85",
    description: "Fluid, wave-inspired sculptural object. A quiet centerpiece for shelves and consoles.",
    material: "Stone-filled PLA",
    dimensions: "28 × 14 × 20 cm",
    leadTime: "Ships in 5–7 days",
  },
  {
    id: "p9",
    name: "Vessel No. 04",
    category: "decor",
    price: 98,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDQ2NDF8MHwxfHNlYXJjaHw0fHxtaW5pbWFsaXN0JTIwZGVjb3J8ZW58MHx8fHwxNzg1MTU3NTk4fDA&ixlib=rb-4.1.0&q=85",
    description: "A ridged decorative vessel that reads as both ancient and future. Watertight for dried arrangements.",
    material: "Ceramic-look PLA",
    dimensions: "Ø 16 × 22 cm",
    leadTime: "Ships in 3–5 days",
  },
  {
    id: "p10",
    name: "Ridge Bookend Pair",
    category: "decor",
    price: 78,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1667312939978-64cf31718a6e?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDQ2NDF8MHwxfHNlYXJjaHwzfHxtaW5pbWFsaXN0JTIwZGVjb3J8ZW58MHx8fHwxNzg1MTU3NTk4fDA&ixlib=rb-4.1.0&q=85",
    description: "A weighted pair of bookends with topographic ridges. Sold as a set of two.",
    material: "Weighted composite",
    dimensions: "12 × 10 × 18 cm each",
    leadTime: "Ships in 3–5 days",
  },
  {
    id: "p11",
    name: "Terra Wall Piece",
    category: "decor",
    price: 210,
    currency: "USD",
    image: "https://images.pexels.com/photos/5793642/pexels-photo-5793642.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    tag: "Limited",
    description: "A textural wall relief inspired by desert landscapes. Made-to-order in earth tones.",
    material: "Terracotta PLA",
    dimensions: "60 × 60 × 4 cm",
    leadTime: "Ships in 10–14 days",
  },
  {
    id: "p12",
    name: "Halo Table Light",
    category: "lamps",
    price: 155,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1765181539706-361512106019?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NzV8MHwxfHNlYXJjaHw0fHxzY3VscHR1cmFsJTIwbGFtcHxlbnwwfHx8fDE3ODUxNTc2MDR8MA&ixlib=rb-4.1.0&q=85",
    description: "A compact ring-shaped light for bedside or desk. Soft glow, generous presence.",
    material: "Matte PLA · Warm LED",
    dimensions: "22 × 8 × 22 cm",
    leadTime: "Ships in 3–5 days",
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Ananya R.",
    role: "Interior Designer, Bengaluru",
    text: "Venus pieces have become the signature detail in every project I finish. They read as sculpture first, functional object second.",
  },
  {
    id: 2,
    name: "Marcus L.",
    role: "Collector, London",
    text: "The craftsmanship is remarkable. My Nova floor lamp arrived flawlessly finished — you can tell every piece is treated as art.",
  },
  {
    id: 3,
    name: "Priya S.",
    role: "Homeowner, Dubai",
    text: "Ordered a custom bust of my late grandfather. The team was patient, thoughtful, and the result moved my entire family.",
  },
];

export const processSteps = [
  { n: "01", title: "Design", copy: "Every form begins as a sketch, then a parametric 3D model refined over weeks." },
  { n: "02", title: "Print", copy: "Printed layer by layer in premium sustainable materials on industrial machines." },
  { n: "03", title: "Finish", copy: "Hand-sanded, sealed and polished in our studio. No two pieces are identical." },
  { n: "04", title: "Deliver", copy: "Packaged with care and shipped worldwide from our workshop." },
];
